import { Arrival } from "./arrival";
import { FlightStatus } from "./flightStatus";

export const allArrivals: Arrival[] = [
    {
        time: "05:15",
        airlineCode: "BA818",
        airlineFin: "/images/tailfins/BA-tailfin.jpg",
        airlineName: "British Airways",
        origin: "Lyon",
        terminal: "T5",
        belt: 8,
        status: FlightStatus.onTime,
    },
    {
        time: "05:20",
        airlineCode: "VS132",
        airlineFin: "/images/tailfins/VS-tailfin.jpg",
        airlineName: "Virgin Atlantic",
        origin: "New York",
        terminal: "T5",
        belt: 6,
        status: FlightStatus.delayed,
    },
    {
        time: "05:30",
        airlineCode: "ET371",
        airlineFin: "/images/tailfins/ET-tailfin.jpg",
        airlineName: "Ethiopian Airlines",
        origin: "Addis Ababa",
        terminal: "T4",
        belt: 3,
        status: FlightStatus.onTime,
    },
    {
        time: "05:50",
        airlineCode: "GF683",
        airlineFin: "/images/tailfins/GF-tailfin.jpg",
        airlineName: "Gulf Air",
        origin: "Manama",
        terminal: "T3",
        belt: 7,
        status: FlightStatus.cancelled,
    },
    {
        time: "06:00",
        airlineCode: "CX243",
        airlineFin: "/images/tailfins/CX-tailfin.jpg",
        airlineName: "Cathay Pacific",
        origin: "Hong Kong",
        terminal: "T4",
        belt: 2,
        status: FlightStatus.onTime,
    },
    {
        time: "06:15",
        airlineCode: "BA43",
        airlineFin: "/images/tailfins/BA-tailfin.jpg",
        airlineName: "British Airways",
        origin: "New York",
        terminal: "T5",
        belt: 4,
        status: FlightStatus.onTime,
    },
    {
        time: "06:55",
        airlineCode: "VN52",
        airlineFin: "/images/tailfins/VN-tailfin.jpg",
        airlineName: "Vietnam Airlines",
        origin: "Hanoi",
        terminal: "T3",
        belt: 5,
        status: FlightStatus.delayed,
    },
    {
        time: "07:30",
        airlineCode: "QR896",
        airlineFin: "/images/tailfins/QR-tailfin.jpg",
        airlineName: "Qatar Airways",
        origin: "Doha",
        terminal: "T4",
        belt: 10,
        status: FlightStatus.onTime,
    },
    {
        time: "07:50",
        airlineCode: "DL2082",
        airlineFin: "/images/tailfins/EU-tailfin.jpg",
        airlineName: "Eurowings",
        origin: "Dusseldorf",
        terminal: "T2",
        belt: 12,
        status: FlightStatus.onTime,
    },
    {
        time: "08:30",
        airlineCode: "VS130",
        airlineFin: "/images/tailfins/VS-tailfin.jpg",
        airlineName: "Virgin Atlantic",
        origin: "Los Angeles",
        terminal: "T5",
        belt: 4,
        status: FlightStatus.delayed,
    },
    {
        time: "08:55",
        airlineCode: "UA2683",
        airlineFin: "/images/tailfins/UA-tailfin.jpg",
        airlineName: "United Airlines",
        origin: "Dallas",
        terminal: "T4",
        belt: 8,
        status: FlightStatus.onTime,
    },
    {
        time: "09:45",
        airlineCode: "JB115",
        airlineFin: "/images/tailfins/JB-tailfin.jpg",
        airlineName: "JetBlue Airlines",
        origin: "Newark",
        terminal: "T3",
        belt: 3,
        status: FlightStatus.onTime,
    },
    {
        time: "10:15",
        airlineCode: "BA825",
        airlineFin: "/images/tailfins/BA-tailfin.jpg",
        airlineName: "British Airways",
        origin: "Riga",
        terminal: "T5",
        belt: 11,
        status: FlightStatus.delayed,
    },
    {
        time: "10:40",
        airlineCode: "SV448",
        airlineFin: "/images/tailfins/SV-tailfin.jpg",
        airlineName: "Saudia Airlines",
        origin: "Riyadh",
        terminal: "T2",
        belt: 11,
        status: FlightStatus.delayed,
    },
    {
        time: "11:00",
        airlineCode: "AI589",
        airlineFin: "/images/tailfins/AI-tailfin.jpg",
        airlineName: "Air India",
        origin: "Mumbai",
        terminal: "T4",
        belt: 6,
        status: FlightStatus.onTime,
    },
    {
        time: "12:00",
        airlineCode: "RO368",
        airlineFin: "/images/tailfins/RO-tailfin.jpg",
        airlineName: "TAROM",
        origin: "Bucharest",
        terminal: "T4",
        belt: 1,
        status: FlightStatus.onTime,
    },
    {
        time: "12:50",
        airlineCode: "KL1368",
        airlineFin: "/images/tailfins/KL-tailfin.jpg",
        airlineName: "KLM",
        origin: "Amsterdam",
        terminal: "T3",
        belt: 2,
        status: FlightStatus.onTime,
    },
    {
        time: "13:20",
        airlineCode: "BA90",
        airlineFin: "/images/tailfins/BA-tailfin.jpg",
        airlineName: "British Airways",
        origin: "Vancouver",
        terminal: "T5",
        belt: 5,
        status: FlightStatus.onTime,
    },
    {
        time: "14:00",
        airlineCode: "RW2575",
        airlineFin: "/images/tailfins/RW-tailfin.jpg",
        airlineName: "Rwanda Air",
        origin: "Kigali",
        terminal: "T3",
        belt: 10,
        status: FlightStatus.onTime,
    },
    {
        time: "14:55",
        airlineCode: "QF808",
        airlineFin: "/images/tailfins/QF-tailfin.jpg",
        airlineName: "Qantas",
        origin: "Perth",
        terminal: "T4",
        belt: 11,
        status: FlightStatus.onTime,
    },
    {
        time: "15:15",
        airlineCode: "JB1720",
        airlineFin: "/images/tailfins/JB-tailfin.jpg",
        airlineName: "JetBlue Airlines",
        origin: "Washington",
        terminal: "T3",
        belt: 8,
        status: FlightStatus.onTime,
    },
    {
        time: "15:45",
        airlineCode: "TG699",
        airlineFin: "/images/tailfins/TG-tailfin.jpg",
        airlineName: "Thai Airways",
        origin: "Bangkok",
        terminal: "T4",
        belt: 15,
        status: FlightStatus.onTime,
    },
    {
        time: "16:35",
        airlineCode: "SQ499",
        airlineFin: "/images/tailfins/SQ-tailfin.jpg",
        airlineName: "Singapore Airlines",
        origin: "Singapore",
        terminal: "T2",
        belt: 12,
        status: FlightStatus.onTime,
    },
    {
        time: "17:00",
        airlineCode: "AV88",
        airlineFin: "/images/tailfins/AV-tailfin.jpg",
        airlineName: "Avianca",
        origin: "Bogota",
        terminal: "T3",
        belt: 7,
        status: FlightStatus.cancelled,
    },
    {
        time: "17:30",
        airlineCode: "BA814",
        airlineFin: "/images/tailfins/BA-tailfin.jpg",
        airlineName: "British Airways",
        origin: "Warsaw",
        terminal: "T5",
        belt: 11,
        status: FlightStatus.delayed,
    },
    {
        time: "17:50",
        airlineCode: "BA800",
        airlineFin: "/images/tailfins/BA-tailfin.jpg",
        airlineName: "British Airways",
        origin: "Larnaca",
        terminal: "T5",
        belt: 1,
        status: FlightStatus.delayed,
    },
    {
        time: "18:40",
        airlineCode: "VS140",
        airlineFin: "/images/tailfins/VS-tailfin.jpg",
        airlineName: "Virgin Atlantic",
        origin: "Las Vegas",
        terminal: "T2",
        belt: 8,
        status: FlightStatus.onTime,
    },
    {
        time: "19:00",
        airlineCode: "AA2323",
        airlineFin: "/images/tailfins/AA-tailfin.jpg",
        airlineName: "American Airlines",
        origin: "Philadelphia",
        terminal: "T3",
        belt: 5,
        status: FlightStatus.onTime,
    },
    {
        time: "20:00",
        airlineCode: "OS979",
        airlineFin: "/images/tailfins/OS-tailfin.jpg",
        airlineName: "Austrian Airlines",
        origin: "Vienna",
        terminal: "T4",
        belt: 6,
        status: FlightStatus.onTime,
    },
    {
        time: "20:25",
        airlineCode: "JL191",
        airlineFin: "/images/tailfins/JL-tailfin.jpg",
        airlineName: "Japan Airlines",
        origin: "Tokyo",
        terminal: "T3",
        belt: 3,
        status: FlightStatus.onTime,
    },
    {
        time: "21:00",
        airlineCode: "CX064",
        airlineFin: "/images/tailfins/CX-tailfin.jpg",
        airlineName: "Cathay Pacific",
        origin: "Hong Kong",
        terminal: "T2",
        belt: 10,
        status: FlightStatus.onTime,
    },
    {
        time: "21:40",
        airlineCode: "DL3644",
        airlineFin: "/images/tailfins/DL-tailfin.jpg",
        airlineName: "Delta Airlines",
        origin: "Detroit",
        terminal: "T4",
        belt: 2,
        status: FlightStatus.cancelled,
    },
    {
        time: "22:25",
        airlineCode: "EH5299",
        airlineFin: "/images/tailfins/EH-tailfin.jpg",
        airlineName: "Etihad Airways",
        origin: "Abu Dhabi",
        terminal: "T2",
        belt: 10,
        status: FlightStatus.onTime,
    },
    {
        time: "22:50",
        airlineCode: "CX111",
        airlineFin: "/images/tailfins/CX-tailfin.jpg",
        airlineName: "Cathay Pacific",
        origin: "Hong Kong",
        terminal: "T2",
        belt: 7,
        status: FlightStatus.cancelled,
    },
];