import { Departure } from "./departure";
import { FlightStatus } from "./fligthStatus";

export const allDepartures: Departure[] = [
    {
        time: "05:00",
        airlineCode: "AH2055",
        airlineFin: "/images/tailfins/AH-tailfin.jpg",
        airlineName: "Air Algerie",
        destination: "Algiers",
        terminal: "T4",
        checkIn: "Hall E",
        gate: 14,
        status: FlightStatus.delayed,
    },
    {
        time: "05:25",
        airlineCode: "CX150",
        airlineFin: "/images/tailfins/CX-tailfin.jpg",
        airlineName: "Cathay Pacific",
        destination: "Hong Kong",
        terminal: "T2",
        checkIn: "Hall B",
        gate: 72,
        status: FlightStatus.onTime,
    },
    {
        time: "05:30",
        airlineCode: "SQ490",
        airlineFin: "/images/tailfins/SQ-tailfin.jpg",
        airlineName: "Singapore Airlines",
        destination: "Singapore",
        terminal: "T2",
        checkIn: "Hall A",
        gate: 24,
        status: FlightStatus.onTime,
    },
    {
        time: "05:45",
        airlineCode: "AC176",
        airlineFin: "/images/tailfins/AC-tailfin.jpg",
        airlineName: "Air Canada",
        destination: "Toronto",
        terminal: "T3",
        checkIn: "Hall B",
        gate: 27,
        status: FlightStatus.cancelled,
    },
    {
        time: "06:15",
        airlineCode: "VS122",
        airlineFin: "/images/tailfins/VS-tailfin.jpg",
        airlineName: "Virgin Atlantic",
        destination: "Boston",
        terminal: "T5",
        checkIn: "Hall A",
        gate: 6,
        status: FlightStatus.onTime,
    },
    {
        time: "06:20",
        airlineCode: "BA165",
        airlineFin: "/images/tailfins/BA-tailfin.jpg",
        airlineName: "British Airways",
        destination: "Cape Town",
        terminal: "T5",
        checkIn: "Hall C",
        gate: 18,
        status: FlightStatus.onTime,
    },
    {
        time: "06:40",
        airlineCode: "AA1313",
        airlineFin: "/images/tailfins/AA-tailfin.jpg",
        airlineName: "American Airlines",
        destination: "Houston",
        terminal: "T2",
        checkIn: "Hall B",
        gate: 64,
        status: FlightStatus.cancelled,
    },
    {
        time: "07:10",
        airlineCode: "AI575",
        airlineFin: "/images/tailfins/AI-tailfin.jpg",
        airlineName: "Air India",
        destination: "Delhi",
        terminal: "T2",
        checkIn: "Hall F",
        gate: 4,
        status: FlightStatus.onTime,
    },
    {
        time: "07:30",
        airlineCode: "AV84",
        airlineFin: "/images/tailfins/AV-tailfin.jpg",
        airlineName: "Avianca",
        destination: "Bogota",
        terminal: "T3",
        checkIn: "Hall A",
        gate: 25,
        status: FlightStatus.onTime,
    },
    {
        time: "07:55",
        airlineCode: "BG677",
        airlineFin: "/images/tailfins/BG-tailfin.jpg",
        airlineName: "Birman Bangladesh Airlines",
        destination: "Dhaka",
        terminal: "T3",
        checkIn: "Hall B",
        gate: 66,
        status: FlightStatus.onTime,
    },
    {
        time: "08:45",
        airlineCode: "BR1044",
        airlineFin: "/images/tailfins/BR-tailfin.jpg",
        airlineName: "Royal Air Brunei",
        destination: "Brunei",
        terminal: "T3",
        checkIn: "Hall A",
        gate: 32,
        status: FlightStatus.delayed,
    },
    {
        time: "10:00",
        airlineCode: "CX158",
        airlineFin: "/images/tailfins/CX-tailfin.jpg",
        airlineName: "Cathay Pacific",
        destination: "Hong Kong",
        terminal: "T2",
        checkIn: "Hall B",
        gate: 70,
        status: FlightStatus.onTime,
    },
    {
        time: "10:20",
        airlineCode: "OS1901",
        airlineFin: "/images/tailfins/OS-tailfin.jpg",
        airlineName: "Austrian Airlines",
        destination: "Vienna",
        terminal: "T4",
        checkIn: "Hall E",
        gate: 13,
        status: FlightStatus.delayed,
    },
    {
        time: "10:40",
        airlineCode: "DL909",
        airlineFin: "/images/tailfins/DL-tailfin.jpg",
        airlineName: "Delta Airlines",
        destination: "Chicago",
        terminal: "T4",
        checkIn: "Hall C",
        gate: 48,
        status: FlightStatus.onTime,
    },
    {
        time: "11:00",
        airlineCode: "EH5354",
        airlineFin: "/images/tailfins/EH-tailfin.jpg",
        airlineName: "Etihad Airways",
        destination: "Abu Dhabi",
        terminal: "T2",
        checkIn: "D",
        gate: 15,
        status: FlightStatus.onTime,
    },
    {
        time: "11:15",
        airlineCode: "VS120",
        airlineFin: "/images/tailfins/VS-tailfin.jpg",
        airlineName: "Virgin Atlantic",
        destination: "Seattle",
        terminal: "T5",
        checkIn: "Hall A",
        gate: 28,
        status: FlightStatus.cancelled,
    },
    {
        time: "11:30",
        airlineCode: "ET373",
        airlineFin: "/images/tailfins/ET-tailfin.jpg",
        airlineName: "Ethiopian Airlines",
        destination: "Addis Ababa",
        terminal: "T2",
        checkIn: "Hall C",
        gate: 40,
        status: FlightStatus.onTime,
    },
    {
        time: "11:40",
        airlineCode: "EU2085",
        airlineFin: "/images/tailfins/EU-tailfin.jpg",
        airlineName: "Eurowings",
        destination: "Dusseldorf",
        terminal: "T3",
        checkIn: "Hall G",
        gate: 9,
        status: FlightStatus.onTime,
    },
    {
        time: "11:45",
        airlineCode: "VN77",
        airlineFin: "/images/tailfins/VN-tailfin.jpg",
        airlineName: "Vietnam Airlines",
        destination: "Hanoi",
        terminal: "T4",
        checkIn: "Hall E",
        gate: 8,
        status: FlightStatus.onTime,
    },
    {
        time: "12:15",
        airlineCode: "GF967",
        airlineFin: "/images/tailfins/GF-tailfin.jpg",
        airlineName: "Gulf Air",
        destination: "Manama",
        terminal: "T4",
        checkIn: "Hall B",
        gate: 60,
        status: FlightStatus.onTime,
    },
    {
        time: "12:40",
        airlineCode: "JB1756",
        airlineFin: "/images/tailfins/JB-tailfin.jpg",
        airlineName: "JetBlue Airlines",
        destination: "Newark",
        terminal: "T3",
        checkIn: "Hall E",
        gate: 16,
        status: FlightStatus.cancelled,
    },
    {
        time: "13:00",
        airlineCode: "JL502",
        airlineFin: "/images/tailfins/JL-tailfin.jpg",
        airlineName: "Japan Airlines",
        destination: "Tokyo",
        terminal: "T4",
        checkIn: "Hall A",
        gate: 57,
        status: FlightStatus.delayed,
    },
    {
        time: "13:50",
        airlineCode: "KL709",
        airlineFin: "/images/tailfins/KL-tailfin.jpg",
        airlineName: "KLM",
        destination: "Amsterdam",
        terminal: "T4",
        checkIn: "Hall C",
        gate: 6,
        status: FlightStatus.onTime,
    },
    {
        time: "14:45",
        airlineCode: "OS899",
        airlineFin: "/images/tailfins/OS-tailfin.jpg",
        airlineName: "Austrian Airlines",
        destination: "Vienna",
        terminal: "T4",
        checkIn: "Hall B",
        gate: 39,
        status: FlightStatus.onTime,
    },
    {
        time: "15:10",
        airlineCode: "AA1425",
        airlineFin: "/images/tailfins/AA-tailfin.jpg",
        airlineName: "American Airlines",
        destination: "Orlando",
        terminal: "T3",
        checkIn: "Hall A",
        gate: 57,
        status: FlightStatus.onTime,
    },
    {
        time: "15:30",
        airlineCode: "QS892",
        airlineFin: "/images/tailfins/QF-tailfin.jpg",
        airlineName: "Qantas",
        destination: "Sydney",
        terminal: "T2",
        checkIn: "Hall G",
        gate: 1,
        status: FlightStatus.delayed,
    },
    {
        time: "16:05",
        airlineCode: "QR124",
        airlineFin: "/images/tailfins/QR-tailfin.jpg",
        airlineName: "Qatar Airways",
        destination: "Doha",
        terminal: "T3",
        checkIn: "Hall G",
        gate: 50,
        status: FlightStatus.onTime,
    },
    {
        time: "16:55",
        airlineCode: "RO365",
        airlineFin: "/images/tailfins/RO-tailfin.jpg",
        airlineName: "TAROM",
        destination: "Bucharest",
        terminal: "T4",
        checkIn: "Hall E",
        gate: 21,
        status: FlightStatus.onTime,
    },
    {
        time: "17:25",
        airlineCode: "RW2415",
        airlineFin: "/images/tailfins/RW-tailfin.jpg",
        airlineName: "Rwanda Air",
        destination: "Kigali",
        terminal: "T3",
        checkIn: "D",
        gate: 70,
        status: FlightStatus.onTime,
    },
    {
        time: "18:10",
        airlineCode: "SQ484",
        airlineFin: "/images/tailfins/SQ-tailfin.jpg",
        airlineName: "Singapore Airlines",
        destination: "Singapore",
        terminal: "T2",
        checkIn: "Hall A",
        gate: 59,
        status: FlightStatus.onTime,
    },
    {
        time: "18:30",
        airlineCode: "CX156",
        airlineFin: "/images/tailfins/CX-tailfin.jpg",
        airlineName: "Cathay Pacific",
        destination: "Hong Kong",
        terminal: "T3",
        checkIn: "Hall B",
        gate: 11,
        status: FlightStatus.delayed,
    },
    {
        time: "18:40",
        airlineCode: "SV444",
        airlineFin: "/images/tailfins/SV-tailfin.jpg",
        airlineName: "Saudia Airlines",
        destination: "Jeddah",
        terminal: "T3",
        checkIn: "Hall F",
        gate: 39,
        status: FlightStatus.onTime,
    },
    {
        time: "19:20",
        airlineCode: "TG697",
        airlineFin: "/images/tailfins/TG-tailfin.jpg",
        airlineName: "Thai Airways",
        destination: "Bangkok",
        terminal: "T4",
        checkIn: "D",
        gate: 55,
        status: FlightStatus.onTime,
    },
    {
        time: "19:50",
        airlineCode: "UA1011",
        airlineFin: "/images/tailfins/UA-tailfin.jpg",
        airlineName: "United Airlines",
        destination: "San Francisco",
        terminal: "T2",
        checkIn: "Hall A",
        gate: 2,
        status: FlightStatus.onTime,
    },
    {
        time: "20:50",
        airlineCode: "VN54",
        airlineFin: "/images/tailfins/VN-tailfin.jpg",
        airlineName: "Vietnam Airlines",
        destination: "Ho Chi Minh City",
        terminal: "T4",
        checkIn: "Hall F",
        gate: 69,
        status: FlightStatus.onTime,
    },
    {
        time: "22:05",
        airlineCode: "VS105",
        airlineFin: "/images/tailfins/VS-tailfin.jpg",
        airlineName: "Virgin Atlantic",
        destination: "Miami",
        terminal: "T5",
        checkIn: "Hall E",
        gate: 46,
        status: FlightStatus.onTime,
    },
    {
        time: "22:20",
        airlineCode: "EH5360",
        airlineFin: "/images/tailfins/EH-tailfin.jpg",
        airlineName: "Etihad Airways",
        destination: "Abu Dhabi",
        terminal: "T2",
        checkIn: "D",
        gate: 17,
        status: FlightStatus.delayed,
    },
    {
        time: "22:30",
        airlineCode: "SQ489",
        airlineFin: "/images/tailfins/SQ-tailfin.jpg",
        airlineName: "Singapore Airlines",
        destination: "Singapore",
        terminal: "T2",
        checkIn: "Hall A",
        gate: 5,
        status: FlightStatus.cancelled,
    },
];